default_agent: schedule_agent
agents:
  schedule_agent:
    name: schedule_agent
    entrypoint: /home/ubuntu/schedule-optimizer/deployment/invoke.py
    platform: linux/arm64
    container_runtime: docker
    source_path: /home/ubuntu/schedule-optimizer/deployment
    aws:
      execution_role: arn:aws:iam::872515288562:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-4cd60f4097
      execution_role_auto_create: false
      account: '872515288562'
      region: us-east-1
      ecr_repository: 872515288562.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-schedule_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: schedule_agent-dQ4rzH2hQC
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:872515288562:runtime/schedule_agent-dQ4rzH2hQC
      agent_session_id: ba5f93e6-2ca5-46b3-9e4c-b50c675e04e6
    codebuild:
      project_name: bedrock-agentcore-schedule_agent-builder
      execution_role: arn:aws:iam::872515288562:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-4cd60f4097
      source_bucket: bedrock-agentcore-codebuild-sources-872515288562-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
